apiVersion: v1
kind: Config
preferences: {}
clusters:
- name: minikube
  cluster:
    server: http://192.168.1.10:8080/auditLogs
users:
- name: default
  user:
    username: default
    password: some-password
contexts:
- name: minikube
  context:
    cluster: minikube
    user: default
current-context: minikube
